set(_CATKIN_CURRENT_PACKAGE "PathPlanner")
set(PathPlanner_VERSION "0.0.0")
set(PathPlanner_MAINTAINER "nandi <nandi@todo.todo>")
set(PathPlanner_PACKAGE_FORMAT "1")
set(PathPlanner_BUILD_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "visualization_msgs")
set(PathPlanner_BUILD_EXPORT_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "visualization_msgs")
set(PathPlanner_BUILDTOOL_DEPENDS "catkin")
set(PathPlanner_BUILDTOOL_EXPORT_DEPENDS )
set(PathPlanner_EXEC_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "visualization_msgs")
set(PathPlanner_RUN_DEPENDS "geometry_msgs" "nav_msgs" "roscpp" "sensor_msgs" "tf" "visualization_msgs")
set(PathPlanner_TEST_DEPENDS )
set(PathPlanner_DOC_DEPENDS )
set(PathPlanner_DEPRECATED "")